using ManagementPortal.Downloaders;
using System;
using System.Threading.Tasks;

namespace ManagementPortal.DownloaderWebSockets;

public class DownloaderWebSocketsAppService : DownloaderWebSocketsAppServiceBase, IDownloaderWebSocketsAppService
{
    private readonly DownloaderConfigService _configService;

    //<suite-custom-code-autogenerated>
    public DownloaderWebSocketsAppService(
        IDownloaderWebSocketRepository downloaderWebSocketRepository,
        DownloaderWebSocketManager downloaderWebSocketManager,
        DownloaderConfigService configService)
        : base(downloaderWebSocketRepository, downloaderWebSocketManager)
    {
        _configService = configService;
    }
    //</suite-custom-code-autogenerated>

    public override async Task<DownloaderWebSocketDto> CreateAsync(DownloaderWebSocketCreateDto input)
    {
        var result = await base.CreateAsync(input);
        await UnitOfWorkManager.Current!.SaveChangesAsync();
        await _configService.ExportToJsonAsync();
        return result;
    }

    public override async Task<DownloaderWebSocketDto> UpdateAsync(Guid id, DownloaderWebSocketUpdateDto input)
    {
        var result = await base.UpdateAsync(id, input);
        await UnitOfWorkManager.Current!.SaveChangesAsync();
        await _configService.ExportToJsonAsync();
        return result;
    }

    public override async Task DeleteAsync(Guid id)
    {
        await base.DeleteAsync(id);
        await UnitOfWorkManager.Current!.SaveChangesAsync();
        await _configService.ExportToJsonAsync();
    }
}