using ManagementPortal.Downloaders;
using ManagementPortal.DownloaderWebSockets;
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;

namespace ManagementPortal.DownloaderWebSockets;

public class DownloaderWebSocketsAppService : DownloaderWebSocketsAppServiceBase, IDownloaderWebSocketsAppService
{
    private readonly DownloaderConfigService _configService;

    //<suite-custom-code-autogenerated>
    public DownloaderWebSocketsAppService(
        IDownloaderWebSocketRepository downloaderWebSocketRepository,
        DownloaderWebSocketManager downloaderWebSocketManager,
        DownloaderConfigService configService)
        : base(downloaderWebSocketRepository, downloaderWebSocketManager)
    {
        _configService = configService;
    }
    //</suite-custom-code-autogenerated>

    public override async Task<DownloaderWebSocketDto> GetAsync(Guid id)
    {
        return await _configService.GetWebSocketAsync(id)
               ?? throw new InvalidOperationException($"WebSocket with id {id} not found.");
    }

    public override async Task<PagedResultDto<DownloaderWebSocketDto>> GetListByDownloaderIdAsync(
        GetDownloaderWebSocketListInput input)
    {
        var list = await _configService.GetWebSocketsByDownloaderIdAsync(input.DownloaderId);
        return new PagedResultDto<DownloaderWebSocketDto>(list.Count, list);
    }

    public override async Task<DownloaderWebSocketDto> CreateAsync(DownloaderWebSocketCreateDto input)
    {
        return await _configService.AddWebSocketAsync(input.DownloaderId, input.Host ?? string.Empty, input.Port);
    }

    public override async Task<DownloaderWebSocketDto> UpdateAsync(Guid id, DownloaderWebSocketUpdateDto input)
    {
        return await _configService.UpdateWebSocketAsync(id, input.Host ?? string.Empty, input.Port);
    }

    public override async Task DeleteAsync(Guid id)
    {
        await _configService.DeleteWebSocketAsync(id);
    }
}
