using ManagementPortal.Downloaders;
using ManagementPortal.DownloaderWebSockets;
using ManagementPortal.Permissions;
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;

namespace ManagementPortal.DownloaderWebSockets;

public class DownloaderWebSocketsAppService : DownloaderWebSocketsAppServiceBase, IDownloaderWebSocketsAppService
{
    private readonly DownloaderConfigService _configService;
    //<suite-custom-code-autogenerated>
    public DownloaderWebSocketsAppService(
        IDownloaderWebSocketRepository downloaderWebSocketRepository, 
        DownloaderWebSocketManager downloaderWebSocketManager, 
        DownloaderConfigService configService) 
        : base(downloaderWebSocketRepository, downloaderWebSocketManager)
    {
        _configService = configService;
    }
    //</suite-custom-code-autogenerated>
    // Override Create → save to JSON file
    public override async Task<DownloaderWebSocketDto> CreateAsync(
        DownloaderWebSocketCreateDto input)
    {
        var existing = await _configService.GetFromFileAsync();

        var newWs = new DownloaderWebSocketDto
        {
            Id = Guid.Parse($"00000000-0000-0000-0000-{(existing.DownloaderWebSockets.Count + 1):D12}"),
            DownloaderId = input.DownloaderId,
            Host = input.Host,
            Port = input.Port
        };

        existing.DownloaderWebSockets.Add(newWs);
        await _configService.SaveToFileAsync(existing);
        return newWs;
    }

    // Override GetAsync to read from JSON file
    public override async Task<DownloaderWebSocketDto> GetAsync(Guid id)
    {
        var config = await _configService.GetFromFileAsync();

        // Find websocket by index (since we use fake Guid ids)
        var ws = config.DownloaderWebSockets.FirstOrDefault();
        if (ws == null)
        {
            throw new Exception("No websocket found in config file.");
        }
        return ws;
    }

    public override async Task<PagedResultDto<DownloaderWebSocketDto>> GetListByDownloaderIdAsync(GetDownloaderWebSocketListInput input)
    {
        var config = await _configService.GetFromFileAsync();
        var list = config.DownloaderWebSockets.Where(x => x.DownloaderId == input.DownloaderId).ToList();
        return new PagedResultDto<DownloaderWebSocketDto>(list.Count, list);
    }

    // Override UpdateAsync to save back to JSON file
    public override async Task<DownloaderWebSocketDto> UpdateAsync(
        Guid id, DownloaderWebSocketUpdateDto input)
    {
        var config = await _configService.GetFromFileAsync();

        // Find and update the websocket
        var ws = config.DownloaderWebSockets
            .FirstOrDefault(x => x.Id == id);

        if (ws != null)
        {
            ws.Host = input.Host;
            ws.Port = input.Port;
        }

        await _configService.SaveToFileAsync(config);
        return ws;
    }

    // Override Delete → remove from JSON file
    public override async Task DeleteAsync(Guid id)
    {
        var existing = await _configService.GetFromFileAsync();

        existing.DownloaderWebSockets = existing.DownloaderWebSockets
            .Where(x => x.Id != id)
            .ToList();

        await _configService.SaveToFileAsync(existing);
    }
}
