using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ManagementPortal.Downloaders;

public class DownloaderManager : DownloaderManagerBase
{
    //<suite-custom-code-autogenerated>
    public DownloaderManager(IDownloaderRepository downloaderRepository) : base(downloaderRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}
