using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace ManagementPortal.Downloaders;

public class Downloader : DownloaderBase
{
    //<suite-custom-code-autogenerated>
    protected Downloader()
    {
    }

    public Downloader(Guid id, bool downloaderEnabled, string? downloaderPollarName = null) : base(id, downloaderEnabled, downloaderPollarName)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}
