using System;
using System.Threading.Tasks;
using Volo.Abp.Caching;

namespace ManagementPortal.Downloaders;

public class DownloadersAppService : DownloadersAppServiceBase, IDownloadersAppService
{
    //<suite-custom-code-autogenerated>
    private readonly DownloaderConfigService _configService;

    public DownloadersAppService(IDownloaderRepository downloaderRepository, DownloaderManager downloaderManager, IDistributedCache<DownloaderDownloadTokenCacheItem, string> downloadTokenCache, DownloaderConfigService configService) : base(downloaderRepository, downloaderManager, downloadTokenCache)
    {
        _configService = configService;
    }
    //</suite-custom-code-autogenerated>

    public override async Task<DownloaderDto> CreateAsync(DownloaderCreateDto input)
    {
        var downloader = new Downloader(GuidGenerator.Create(), input.DownloaderEnabled, input.DownloaderPollarName)
        {
            DownstreamHealthFile = input.DownstreamHealthFile
        };
        downloader = await _downloaderRepository.InsertAsync(downloader, autoSave: true);
        await _configService.ExportToJsonAsync();
        return ObjectMapper.Map<Downloader, DownloaderDto>(downloader);
    }

    public override async Task<DownloaderDto> UpdateAsync(Guid id, DownloaderUpdateDto input)
    {
        var downloader = await _downloaderRepository.GetAsync(id);
        downloader.DownloaderEnabled = input.DownloaderEnabled;
        downloader.DownloaderPollarName = input.DownloaderPollarName;
        downloader.DownstreamHealthFile = input.DownstreamHealthFile;
        if (input.ConcurrencyStamp != null)
            downloader.ConcurrencyStamp = input.ConcurrencyStamp;
        downloader = await _downloaderRepository.UpdateAsync(downloader, autoSave: true);
        await _configService.ExportToJsonAsync();
        return ObjectMapper.Map<Downloader, DownloaderDto>(downloader);
    }

    public override async Task DeleteAsync(Guid id)
    {
        await _downloaderRepository.DeleteAsync(id, autoSave: true);
        await _configService.ExportToJsonAsync();
    }

    public async Task<int> GetMaxWorkerAsync()
    {
        return await _configService.GetMaxWorkerAsync();
    }

    public async Task SetMaxWorkerAsync(int maxWorker)
    {
        await _configService.SetMaxWorkerAsync(maxWorker);
    }
}