using ManagementPortal.DownloaderWebSockets;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Caching;

namespace ManagementPortal.Downloaders;

public class DownloadersAppService : DownloadersAppServiceBase, IDownloadersAppService
{
    //<suite-custom-code-autogenerated>'
    private readonly DownloaderConfigService _configService;

    public DownloadersAppService(IDownloaderRepository downloaderRepository, DownloaderManager downloaderManager, IDistributedCache<DownloaderDownloadTokenCacheItem, string> downloadTokenCache, DownloaderConfigService configService) : base(downloaderRepository, downloaderManager, downloadTokenCache)
    {
        _configService = configService;
    }
    //</suite-custom-code-autogenerated>

    public override async Task<PagedResultDto<DownloaderDto>> GetListAsync(GetDownloadersInput input)
    {
        return await _configService.GetPagedListFromFileAsync(
           input.FilterText,
           input.DownloaderPollarName,
           input.DownloaderEnabled);
    }

    public override async Task<DownloaderDto> GetAsync(Guid id)
    {
        return await _configService.GetFromFileAsync(id)
               ?? throw new InvalidOperationException($"Downloader with id {id} not found.");
    }

    public override async Task<DownloaderDto> CreateAsync(DownloaderCreateDto input)
    {
        var dto = new DownloaderDto
        {
            DownloaderEnabled = input.DownloaderEnabled,
            DownloaderPollarName = input.DownloaderPollarName,
            DownstreamHealthFile = input.DownstreamHealthFile,
            DownloaderWebSockets = new List<DownloaderWebSocketDto>()
        };
        return await _configService.AddToFileAsync(dto);
    }

    public override async Task<DownloaderDto> UpdateAsync(Guid id, DownloaderUpdateDto input)
    {
        var existing = await _configService.GetFromFileAsync(id);
        var dto = new DownloaderDto
        {
            DownloaderEnabled = input.DownloaderEnabled,
            DownloaderPollarName = input.DownloaderPollarName,
            DownstreamHealthFile = input.DownstreamHealthFile,
            DownloaderWebSockets = input.DownloaderWebSockets.Any()
                ? input.DownloaderWebSockets
                : existing?.DownloaderWebSockets ?? new List<DownloaderWebSocketDto>()
        };
        return await _configService.UpdateInFileAsync(id, dto);
    }

    public override async Task DeleteAsync(Guid id)
    {
        await _configService.DeleteFromFileAsync(id);
    }

    public async Task<int> GetMaxWorkerAsync()
    {
        return await _configService.GetMaxWorkerAsync();
    }

    public async Task SetMaxWorkerAsync(int maxWorker)
    {
        await _configService.SetMaxWorkerAsync(maxWorker);
    }
}
