using ManagementPortal.DownloaderWebSockets;
using System;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Caching;

namespace ManagementPortal.Downloaders;

public class DownloadersAppService : DownloadersAppServiceBase, IDownloadersAppService
{
    //<suite-custom-code-autogenerated>'
    private readonly DownloaderConfigService _configService;

    public DownloadersAppService(IDownloaderRepository downloaderRepository, DownloaderManager downloaderManager, IDistributedCache<DownloaderDownloadTokenCacheItem, string> downloadTokenCache, DownloaderConfigService configService) : base(downloaderRepository, downloaderManager, downloadTokenCache)
    {
        _configService = configService;
    }
    //</suite-custom-code-autogenerated>

    public override async Task<PagedResultDto<DownloaderDto>> GetListAsync(GetDownloadersInput input)
    {
        return await _configService.GetPagedListFromFileAsync(
           input.FilterText,
           input.DownloaderPollarName,
           input.DownloaderEnabled);
    }

    public override async Task<DownloaderDto> CreateAsync(
    DownloaderCreateDto input)
    {
        var config = await _configService.GetFromFileAsync();
        // map input to dto and save
        config.DownloaderEnabled = input.DownloaderEnabled;
        config.DownloaderPollarName = input.DownloaderPollarName;
        await _configService.SaveToFileAsync(config);
        return config;
    }

    public override async Task<DownloaderDto> UpdateAsync(
        Guid id, DownloaderUpdateDto input)
    {
        var existing = await _configService.GetFromFileAsync();
        var newDto = new DownloaderDto
        {
            DownloaderEnabled = input.DownloaderEnabled,
            DownloaderPollarName = input.DownloaderPollarName,
            DownloaderWebSockets = input.DownloaderWebSockets.Any()
                ? input.DownloaderWebSockets
                : existing.DownloaderWebSockets
        };
        await _configService.SaveToFileAsync(newDto);
        return await _configService.GetFromFileAsync();
    }

    public override async Task<DownloaderDto> GetAsync(Guid id)
    {
        // ignore the id, just return from JSON file
        return await _configService.GetFromFileAsync();
    }
}
