using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ManagementPortal.DownloaderWebSockets;

public class DownloaderWebSocketManager : DownloaderWebSocketManagerBase
{
    //<suite-custom-code-autogenerated>
    public DownloaderWebSocketManager(IDownloaderWebSocketRepository downloaderWebSocketRepository) : base(downloaderWebSocketRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}
