using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace ManagementPortal.DownloaderWebSockets;

public class DownloaderWebSocket : DownloaderWebSocketBase
{
    //<suite-custom-code-autogenerated>
    protected DownloaderWebSocket()
    {
    }

    public DownloaderWebSocket(Guid id, Guid downloaderId, int port, string? host = null) : base(id, downloaderId, port, host)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}
